# Generated by Django 5.0 on 2024-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
            },
        ),
    ]
